baseurl = "http://your-site-here/"
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
title = "your site title"
# theme = "hugo-theme-geppaku"
googleAnalytics = "G-2GMRFCH6DG" # Optional
disqusShortname = "" # Optional

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.ja]
    languageName = "Japanese"
    weight = 2

[author]
    # If you want to display author information set these
    # This is Optional values
    name = "Your name"

    # Please set account ids
    # This is Optional values
    x_twitter  = "your twitter id"
    linkedin   = "your linkedin id"
    github     = "your github id"
    bluesky    = "your bluesky id"

[params]
    [params.sharebutton]
        # If you want to display share buttons set these
        # This is Optional values
        x_twitter  = true
        # facebook = true
        # hatena     = true # hatena is Japanese social media
        google     = true
        # pocket     = true
        # Please set id when you want to display facebook
        # facebookAppId = "your app id"
        bluesky    = true

    [params.adsense]
        # If you want to display Google adsense set these
        # This is Optional values
        # 1. Create file written of the adsense tag into the directory "layouts/partials"
        # 2. Please set file path name omitted "layouts/partials"
        # sidebar = "adsense/sidebar.html"
        # content = "adsense/content.html"
