name: Deploy to github pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.132.2'
          extended: false
      - name: Build
        run: |
          export BASE_URL="https://koooge.github.io/hugo-theme-geppaku/"
          hugo --gc --minify --config ./exampleSite/config/test/config.toml --themesDir ./ --layoutDir ./layouts --baseURL "${BASE_URL}"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
