name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npx stylelint '**/*.css'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.132.2'
          extended: false
      - name: Build
        run: |
          export BASE_URL="https://koooge.github.io/hugo-theme-geppaku/"
          hugo --gc --minify --configDir ./exampleSite/config --config ./exampleSite/config/test/config.toml --themesDir ./ --layoutDir ./layouts --contentDir ./exampleSite/content --baseURL "${BASE_URL}"
